name: 'airbnb_dbt'
version: '1.0.0'
profile: 'airbnb_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbnb_dbt:
    bronze:
      +schema: bronze
      +materialized: table
      +tags: ["bronze"]
    silver:
      +schema: silver
      +materialized: table
      +tags: ["silver"]
    gold:
      +schema: gold
      +materialized: table
      +tags: ["gold"]
