# dbt_project.yml

name: 'airbnb_dbt'
version: '1.0.0'
profile: 'airbnb_dbt'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  airbnb_launch_date: '2008-08-01'

seeds:
  airbnb_dbt:
    +schema: seeds

snapshots:
  airbnb_dbt:
    +schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

    
models:
  airbnb_dbt:
    staging:
      +schema: staging
      +materialized: view
    silver:
      +schema: silver
      +materialized: incremental
    gold:
      core:
        +schema: core
        +materialized: table
      marts:
        +schema: marts
        +materialized: view
