sources:
  - name: staging    # this matches the first argument in {{ source()}}
    database: AIRBNB
    schema: staging  # this is the real schema
    tables:
      - name: bookings  # this matches the second argument
      - name: listings  # this matches the second argument
      - name: hosts     # this matches the second argument

